development:
  adapter: postgresql
  database: DATABASE
  username: USERNAME
  password: PASSWORD
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: DATABASE
  username: USERNAME
  password: PASSWORD
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: DATABASE
  username: USERNAME
  password: PASSWORD
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000